doc:Doxyfile #../src/*.h ../test/src/*.h
	doxygen Doxyfile

#	cp -s html/index.html ../doc.html

clean:
	rm -vfr html
	rm -vf *.pdf
	rm -vf *.aux
	rm -vf *.toc
	rm -vf *.log
	rm -vf *.nav
	rm -vf *.snm
	rm -vf *.out
	rm -vf *~
	rm -vf ../*.html *.html
